### ISSUE TITLE
I'm a user of GoSublime

### ISSUE THREAD

**Issue by ardan-bkennedy** [golang/sublime-config#5]
I feel like I am missing a lot right now. Today I can configure what happens when I hit save. Which is clearing the command window, running go build -i, go vet and golint. I can't lose this functionality. Not that excited about using command B instead of save.

I was hoping the new plugin would provide better support for code completion and navigating around the code. The navigation piece is what has the most issues in GoSublime. It can be a hit or miss using command . G

**Comment by wbond** [comment]
I think you may have intended to post this on https://github.com/golang/sublime-build. This repository is for a common configuration Python module that provides a simple API for Sublime Text package developers to get info about a user's Go environment.

That said, this sounds like more of a discussion item than a bug/issue. I think https://forum.golangbridge.org/t/sublime-text-build-system-integration-packages-v0-9-0/1432 may be good place to discuss thoughts on what you'd like to see for future Sublime Text integration.

**Comment by ardan-bkennedy** [comment]
Oops, thanks for the heads up.
