### ISSUE TITLE
Collect env vars from `go env`

### ISSUE THREAD

**Issue by wy-z** [golang/sublime-config#8]
It seems that some variables may not exist in system environment variable list, but exist in `go env`.
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/someone/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kz/6s_svz017zv1w1p6vdy414v00000gn/T/go-build651194334=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

[GO 1.8 - Default GOPATH](https://golang.org/doc/go1.8#gopath)

**Comment by wy-z** [comment]
@wbond

**Comment by wbond** [comment]
@wy-z Just to set your expectations, I don't have access to anything on this repo, it has to go through the Go team (via Gerrit the last time I worked on it). Also, I haven't had time for open source recently, so I am probably not very likely to be helpful.

**Comment by wy-z** [comment]
Oh, I see. Thank you anyway~ @wbond
